USE GD1C2023
GO


/* CREANDO SCHEMA */
CREATE SCHEMA PEDIDOS_APP
GO

/* CREANDO TABLAS */

CREATE TABLE PEDIDOS_APP.RECLAMO (
	RECLAMO_NRO decimal(18,0) PRIMARY KEY,
	RECLAMO_TIPO nvarchar(50) ,
	RECLAMO_ESTADO nvarchar(50),
	RECLAMO_DESCRIPCION nvarchar(50),
	RECLAMO_SOLUCION nvarchar(255),
	RECLAMO_FECHA datetime2(3) ,
	RECLAMO_CALIFICACION decimal(18,0),
	USUARIO_DNI decimal(18,0),
	PEDIDO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.CUPON(
	CUPON_NRO decimal(18,0) PRIMARY KEY,
	CUPON_MONTO decimal(18,2),
	CUPON_TIPO nvarchar(50),
	CUPON_FECHA_ALTA datetime2(3),
	CUPON_FECHA_VENCIMIENTO datetime2(3),
);

CREATE TABLE PEDIDOS_APP.CUPON_RECLAMO(
	CUPON_RECLAMO_NRO decimal(18,0) PRIMARY KEY,
	CUPON_RECLAMO_MONTO decimal(18,2),
	CUPON_RECLAMO_FECHA_ALTA datetime2 (3),
	CUPON_RECLAMO_FECHA_VENCIMIENTO datetime2(3),
	CUPON_RECLAMO_TIPO nvarchar(50),
	RECLAMO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.USUARIO_X_CUPON(
	USUARIO_X_CUPON_NRO decimal(18,0) PRIMARY KEY,
	CUPON_NRO decimal(18,0),
	USUARIO_DNI decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.PEDIDO_X_CUPON(
	PEDIDO_X_CUPON_NRO decimal(18,0) PRIMARY KEY,
	CUPON_NRO decimal(18,0),
	PEDIDO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.PRODUCTO_X_PEDIDO(
	PEDIDO_NRO decimal(18,0),
	PRODUCTO_LOCAL_CODIGO nvarchar(50),
	PRODUCTO_CANTIDAD decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.PRODUCTO_LOCAL(
	PRODUCTO_LOCAL_CODIGO nvarchar(50) PRIMARY KEY,
	PRODUCTO_LOCAL_PRECIO decimal(18,2),
	PRODUCTO_LOCAL_NOMBRE nvarchar(50),
	PRODUCTO_LOCAL_DESCRIPCION nvarchar(255),
	LOCAL_CODIGO nvarchar(50),
);

CREATE TABLE PEDIDOS_APP.PEDIDO(
	PEDIDO_NRO decimal(18,0) PRIMARY KEY,
	PEDIDO_TOTAL_PRODUCTOS decimal(18,2),
	PEDIDO_PRECIO_ENVIO decimal(18,2),
	PEDIDO_TARIFA_SERVICIO decimal(18,2),
	PEDIDO_PROPINA decimal(18,2),
	PEDIDO_OBSERV nvarchar(255),
	PEDIDO_TOTAL_CUPONES decimal(18,2),
	PEDIDO_TOTAL_SERVICIO decimal(18,2),
	PEDIDO_FECHA datetime2(3),
	PEDIDO_FECHA_ENTREGA datetime2(3),
	PEDIDO_TIEMPO_ESTIMADO_ENTREGA decimal(18,2),
	MEDIO_DE_PAGO_NRO_TARJETA decimal(16,0),
	LOCAL_CODIGO nvarchar(50),
	USUARIO_DNI decimal(18,0),
	/*REPARTIDOR_DNI decimal(18,0) No se si ponerlo al dni del repartido aca o en otro envio*/
);

CREATE TABLE PEDIDOS_APP.USUARIO(
	USUARIO_DNI decimal(18,0),
	USUARIO_NOMBRE nvarchar(255),
	USUARIO_APELLIDO nvarchar(255),
	USUARIO_FECHA_REGISTRO datetime2(3),
	USUARIO_TELEFONO decimal(18,0),
	USUARIO_MAIL nvarchar(255),
	USUARIO_FECHA_NAC date,
	MEDIO_DE_PAGO_NRO_TARJETA decimal(16,0)
);
CREATE TABLE PEDIDOS_APP.REPARTIDOR(
	REPARTIDOR_DNI decimal(18,0),
	REPARTIDOR_NOMBRE nvarchar(255),
	REPARTIDOR_APELLIDO nvarchar(255),
	REPARTIDOR_TELEFONO decimal(18,0),
	REPARTIDOR_MAIL nvarchar(255),
	REPARTIDOR_FECHA_NAC date,
	REPARTIDOR_TIPO_MOVILIDAD nvarchar(50)
);/*Decidir si ponerle la direccion como una fk o como nvchar como en el master
	Ademas de que no existe el tipo envio como si en la tabla, */

CREATE TABLE PEDIDOS_APP.OPERADOR(
	REPARTIDOR_DNI decimal(18,0),
	REPARTIDOR_NOMBRE nvarchar(255),
	REPARTIDOR_APELLIDO nvarchar(255),
	REPARTIDOR_TELEFONO decimal(18,0),
	REPARTIDOR_MAIL nvarchar(255),
	REPARTIDOR_FECHA_NAC date,
);/*Decidir si ponerle la direccion como una fk o como nvchar como en el master*/

CREATE TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR(
	RECLAMO_X_OPERADOR_NRO decimal(18,0) PRIMARY KEY,
	OPERADOR_DNI decimal(18,0),
	RECLAMO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.ENVIO_MENSAJERIA(
	ENVIO_MENSAJERIA_NRO decimal(18,0) PRIMARY KEY,
	ENVIO_MENSAJERIA_DIR_ROIG nvarchar(255),
	ENVIO_MENSAJERIA_DIR_DEST nvarchar(255),
	ENVIO_MENSAJERIA_LOCALIDAD nvarchar(255),
	ENVIO_MENSAJERIA_PROVINCIA nvarchar(255),
	ENVIO_MENSAJERIA_KM decimal(18,2),
	ENVIO_MENSAJERIA_VALOR_ASEGURADO decimal(18,2),
	ENVIO_MENSAJERIA_PRECIO_ENVIO decimal(18,2),
	ENVIO_MENSAJERIA_PRECIO_SEGURO decimal(18,2),
	ENVIO_MENSAJERIA_PROPINA decimal (18,2),
	ENVIO_MENSAJERIA_TOTAL decimal(18,2),
	ENVIO_MENSAJERIA_OBSERV nvarchar(255),
	ENVIO_MENSAJERIA_FECHA datetime,
	ENVIO_MENSAJERIA_ENTREGA datetime,
	ENVIO_MENSAJERIA_TIEMPO_ESTIMADO decimal(18,2),
	ENVIO_MENSAJERIA_CALIFICACION decimal(18,0),
	USUARIO_DNI decimal(18,0),
	REPARTIDOR_DNI decimal(18,0),
	MEDIO_PAGO_NRO_TARJETA nvarchar(50),
	PAQUETE_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.MEDIO_PAGO(
	MEDIO_PAGO_NRO_TARJETA nvarchar(50) PRIMARY KEY,
	MEDIO_PAGO_TIPO nvarchar(50),
	MARCA_TARJETA nvarchar(100),
	USUARIO_DNI decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.PAQUETE(
	PAQUETE_NRO decimal(18,0) PRIMARY KEY,
	PAQUETE_TIPO nvarchar(50),
	PAQUETE_ALTO_MAX decimal(18,2),
	PAQUETE_ANCHO_MAX decimal(18,2),
	PAQUETE_LARGO_MAX decimal(18,2),
	PAQUETE_PESO_MAX decimal(18,2),
	PAQUETE_TIPO_PRECIO decimal(18,2),
	ENVIO_MENSAJERIA_NRO decimal(18,2)
);

CREATE TABLE PEDIDOS_APP.HORARIO_LOCAL(
	HORARIO_LOCAL_HORA_APERTURA decimal(18,0),
	HORARIO_LOCAL_HORA_CIERRE decimal(18,0),
	HORARIO_LOCAL_DIA nvarchar(50),
	LOCAL_NRO decimal(18,0)
);

/* CREACION DE FOREIGN KEYS */

ALTER TABLE PEDIDOS_APP.RECLAMO ADD CONSTRAINT FK_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO ADD CONSTRAINT FK_PEDIDO_NRO FOREIGN KEY (PEDIDO_NRO) REFERENCES PEDIDOS_APP.PEDIDO(PEDIDO_NRO)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO_X_CUPON ADD CONSTRAINT FK_CUPON_NRO FOREIGN KEY (CUPON_NRO) REFERENCES PEDIDOS_APP.CUPON(CUPON_NRO)
GO

ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON ADD CONSTRAINT FK_CUPON_NRO FOREIGN KEY (CUPON_NRO) REFERENCES PEDIDOS_APP.CUPON(CUPON_NRO)
GO

ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON ADD CONSTRAINT FK_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO_X_CUPON ADD CONSTRAINT FK_PEDIDO_NRO FOREIGN KEY (PEDIDO_NRO) REFERENCES PEDIDOS_APP.PEDIDO(PEDIDO_NRO)
GO

ALTER TABLE PEDIDOS_APP.CUPON_RECLAMO ADD CONSTRAINT FK_RECLAMO_NRO FOREIGN KEY (RECLAMO_NRO) REFERENCES PEDIDOS_APP.RECLAMO(RECLAMO_NRO)
GO

ALTER TABLE PEDIDOS_APP.PRODUCTO_X_PEDIDO ADD CONSTRAINT FK_PEDIDO_NRO FOREIGN KEY (PEDIDO_NRO) REFERENCES PEDIDOS_APP.PEDIDO(PEDIDO_NRO)
GO

ALTER TABLE PEDIDOS_APP.PRODUCTO_LOCAL ADD CONSTRAINT FK_LOCAL_NRO FOREIGN KEY (LOCAL_CODIGO) REFERENCES PEDIDOS_APP.LOCAL(LOCAL_CODIGO)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_LOCAL_CODIGO FOREIGN KEY (LOCAL_CODIGO) REFERENCES PEDIDOS_APP.LOCAL(LOCAL_CODIGO)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_MEDIO_DE_PAGO_NRO_TARJETA FOREIGN KEY (MEDIO_DE_PAGO_NRO_TARJETA) REFERENCES PEDIDOS_APP.MEDIO_DE_PAGO(MEDIO_DE_PAGO_NRO_TARJETA)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

/*
ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_REPARTIDOR_DNI FOREIGN KEY (REPARTIDOR_DNI) REFERENCES PEDIDOS_APP.REPARTIDOR(REPARTIDOR_DNI)
GO
Este es si nos decidimos si el pedido cuenta como envio y ponemos el DNI del repartidor ahi o no
*/

ALTER TABLE PEDIDOS_APP.USUARIO ADD CONSTRAINT FK_MEDIO_PAGO_NRO FOREIGN KEY (MEDIO_PAGO_NRO) REFERENCES PEDIDOS_APP.MEDIO_DE_PAGO(MEDIO_PAGO_NRO)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR ADD CONSTRAINT FK_RECLAMO_NRO FOREIGN KEY (RECLAMO_NRO) REFERENCES PEDIDOS_APP.RECLAMO(RECLAMO_NRO)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR ADD CONSTRAINT FK_OPERADOR_DNI FOREIGN KEY (OPERADOR_DNI) REFERENCES PEDIDOS_APP.OPERADOR(OPERADOR_DNI)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_REPARTIDOR_DNI FOREIGN KEY (REPARTIDOR_DNI) REFERENCES PEDIDOS_APP.REPARTIDOR(REPARTIDOR_DNI)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_MEDIO_PAGO_NRO_TARJETA FOREIGN KEY (MEDIO_PAGO_NRO_TARJETA) REFERENCES PEDIDOS_APP.MEDIO_DE_PAGO(MEDIO_PAGO_NRO_TARJETA)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_PAQUETE_NRO FOREIGN KEY (PAQUETE_NRO) REFERENCES PEDIDOS_APP.PAQUETE(PAQUETE_NRO)
GO

ALTER TABLE PEDIDOS_APP.MEDIO_DE_PAGO ADD CONSTRAINT FK_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO)
GO

ALTER TABLE PEDIDOS_APP.PAQUETE ADD CONSTRAINT FK_ENVIO_MENSAJERIA_NRO FOREIGN KEY (ENVIO_MENSAJERIA_NRO) REFERENCES PEDIDOS_APP.ENVIO_MENSAJERIA(ENVIO_MENSAJERIA_NRO)
GO

ALTER TABLE PEDIDOS_APP.HORARIO_LOCAL ADD CONSTRAINT FK_LOCAL_NRO FOREIGN KEY (LOCAL_CODIGO) REFERENCES PEDIDOS_APP.LOCAL(LOCAL_CODIGO)
GO