USE GD1C2023
GO

/* DROP FK */
IF OBJECT_ID ('PEDIDOS_APP.FK_ENVIO_REPARTIDOR_DNI', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.ENVIO DROP CONSTRAINT FK_ENVIO_REPARTIDOR_DNI
GO 

IF OBJECT_ID ('PEDIDO_APP.FK_ENVIO_PEDIDO_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.ENVIO DROP CONSTRAINT FK_ENVIO_PEDIDO_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_RECLAMO_CUPON_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.RECLAMO DROP CONSTRAINT FK_RECLAMO_CUPON_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_RECLAMO_DNI', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.RECLAMO DROP CONSTRAINT FK_RECLAMO_DNI
GO 

IF OBJECT_ID ('PEDIDOS_APP.FK_RECLAMO_PEDIDO_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.RECLAMO DROP CONSTRAINT FK_RECLAMO_PEDIDO_NRO
GO

IF OBJECT_ID('PEDIDOS_APP.FK_REPARTIDOR_TIPO_MOVILIDAD_COD', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.REPARTIDOR DROP CONSTRAINT FK_REPARTIDOR_TIPO_MOVILIDAD_COD
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_USUARIO_DIRECCION_DNI' , 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.USUARIO_DIRECCION DROP CONSTRAINT FK_USUARIO_DIRECCION_DNI
GO


IF OBJECT_ID('PEDIDOS_APP.FK_LOCAL_HORARIO_LOCAL_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.LOCAL DROP CONSTRAINT FK_LOCAL_HORARIO_LOCAL_NRO
GO

IF OBJECT_ID('PEDIDOS_APP.FK_HORARIO_LOCAL_LOCAL_CODIGO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.HORARIO_LOCAL DROP CONSTRAINT FK_HORARIO_LOCAL_LOCAL_CODIGO
GO

IF OBJECT_ID('PEDIDOS_APP.FK_PAQUETE_ENVIO_MENSAJERIA_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.PAQUETE DROP CONSTRAINT FK_PAQUETE_ENVIO_MENSAJERIA_NRO
GO

IF OBJECT_ID('PEDIDOS_APP.FK_MEDIO_PAGO_USUARIO_DNI', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.MEDIO_PAGO DROP CONSTRAINT FK_MEDIO_PAGO_USUARIO_DNI
GO

IF OBJECT_ID('PEDIDOS_APP.FK_ENVIO_MENSAJERIA_PAQUETE_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA DROP CONSTRAINT FK_ENVIO_MENSAJERIA_PAQUETE_NRO
GO

IF OBJECT_ID('PEDIDOS_APP.FK_ENVIO_MENSAJERIA_MEDIO_PAGO_NRO_TARJETA', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA DROP CONSTRAINT FK_ENVIO_MENSAJERIA_MEDIO_PAGO_NRO_TARJETA
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_ENVIO_MENSAJERIA_USUARIO_DNI' , 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA DROP CONSTRAINT FK_ENVIO_MENSAJERIA_USUARIO_DNI
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_ENVIO_MENSAJERIA_REPARTIDOR_DNI', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA DROP CONSTRAINT FK_ENVIO_MENSAJERIA_REPARTIDOR_DNI
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_RECLAMO_X_OPERADOR_OPERADOR_DNI', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR DROP CONSTRAINT FK_RECLAMO_X_OPERADOR_OPERADOR_DNI
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_RECLAMO_X_OPERADOR_RECLAMO_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR DROP CONSTRAINT FK_RECLAMO_X_OPERADOR_RECLAMO_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_USUARIO_MEDIO_PAGO_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.USUARIO DROP CONSTRAINT FK_USUARIO_MEDIO_PAGO_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_PEDIDO_USUARIO_DNI', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.PEDIDO DROP CONSTRAINT FK_PEDIDO_USUARIO_DNI
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_USUARIO_CUPON_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON DROP CONSTRAINT FK_USUARIO_CUPON_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_U_X_C_CUPON_USUARIO_DNI') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON DROP CONSTRAINT FK_U_X_C_USUARIO_DNI
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_P_X_C_PEDIDO_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.PEDIDO_X_CUPON DROP CONSTRAINT FK_P_X_C_PEDIDO_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_CUPONR_RECLAMO_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.CUPON_RECLAMO DROP CONSTRAINT FK_CUPONR_RECLAMO_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_PRODUCTO_X_PEDIDO_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.PRODUCTO_X_PEDIDO DROP CONSTRAINT FK_PRODUCTO_X_PEDIDO_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_PRODUCTO_LOCAL_LOCAL_NRO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.PRODUCTO_LOCAL DROP CONSTRAINT FK_PRODUCTO_LOCAL_LOCAL_NRO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_PEDIDO_LOCAL_CODIGO', 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.PEDIDO DROP CONSTRAINT FK_PEDIDO_LOCAL_CODIGO
GO

IF OBJECT_ID ('PEDIDOS_APP.FK_PEDIDO_MEDIO_PAGO_NRO_TARJETA' , 'F') IS NOT NULL
	ALTER TABLE PEDIDOS_APP.PEDIDO DROP CONSTRAINT FK_PEDIDO_MEDIO_PAGO_NRO_TARJETA
GO

/* DROP TABLES */
IF OBJECT_ID('PEDIDOS_APP.RECLAMO', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.RECLAMO
GO

IF OBJECT_ID('PEDIDOS_APP.CUPON', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.CUPON
GO

IF OBJECT_ID('PEDIDOS_APP.CUPON_RECLAMO', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.CUPON_RECLAMO
GO

IF OBJECT_ID('PEDIDOS_APP.USUARIO_X_CUPON', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.USUARIO_X_CUPON
GO

IF OBJECT_ID ('PEDIDOS_APP.PEDIDO_X_CUPON','U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.PEDIDO_X_CUPON
GO 

IF OBJECT_ID ('PEDIDOS_APP.PRODUCTO_X_PEDIDO', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.PRODUCTO_X_PEDIDO
GO

IF OBJECT_ID('PEDIDOS_APP.PEDIDO', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.PEDIDO
GO

IF OBJECT_ID ('PEDIDOS_APP.PRODUCTO_LOCAL', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.PRODUCTO_LOCAL
GO

IF OBJECT_ID ('PEDIDOS_APP.USUARIO', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.USUARIO
GO

IF OBJECT_ID('PEDIDOS_APP.REPARTIDOR', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.REPARTIDOR
GO

IF OBJECT_ID('PEDIDOS_APP.OPERADOR', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.OPERADOR
GO

IF OBJECT_ID ('PEDIDOS_APP.RECLAMO_X_OPERADOR', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR
GO

IF OBJECT_ID ('PEDIDOS_APP.ENVIO_MENSAJERIA', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.ENVIO_MENSAJERIA
GO

IF OBJECT_ID ('PEDIDOS_APP.MEDIO_PAGO', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.MEDIO_PAGO
GO

IF OBJECT_ID ('PEDIDOS_APP.PAQUETE', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.PAQUETE 
GO

IF OBJECT_ID ('PEDIDOS_APP.LOCAL', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.LOCAL
GO

IF OBJECT_ID ('PEDIDOS_APP.TIPO_MOVILIDAD', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.TIPO_MOVILIDAD
GO

IF OBJECT_ID ('PEDIDOS_APP.HORARIO_LOCAL','U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.HORARIO_LOCAL
GO

IF OBJECT_ID('PEDIDOS_APP.USUARIO_DIRECCION', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.USUARIO_DIRECCION
GO 

IF OBJECT_ID('PEDIDOS_APP.ENVIO', 'U') IS NOT NULL
	DROP TABLE PEDIDOS_APP.ENVIO
GO

/* DROP SCHEMA */
IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'PEDIDOS_APP')
	DROP SCHEMA PEDIDOS_APP
GO


/* CREANDO SCHEMA */
CREATE SCHEMA PEDIDOS_APP
GO

/* CREANDO TABLAS */

CREATE TABLE PEDIDOS_APP.RECLAMO (
	RECLAMO_NRO decimal(18,0) PRIMARY KEY,
	RECLAMO_TIPO nvarchar(50) ,
	RECLAMO_ESTADO nvarchar(50),
	RECLAMO_DESCRIPCION nvarchar(50),
	RECLAMO_SOLUCION nvarchar(255),
	RECLAMO_FECHA datetime2(3) ,
	RECLAMO_CALIFICACION decimal(18,0),
	USUARIO_DNI decimal(18,0),
	PEDIDO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.ENVIO (
	PEDIDO_NRO decimal(18,0) PRIMARY KEY,
	ENVIO_DIRECCION nvarchar(255),
	ENVIO_PRECIO decimal(18,2),
	ENVIO_PROPINA decimal(18,2),
	REPARTIDOR_DNI decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.CUPON(
	CUPON_NRO decimal(18,0) PRIMARY KEY,
	CUPON_MONTO decimal(18,2),
	CUPON_TIPO nvarchar(50),
	CUPON_FECHA_ALTA datetime2(3),
	CUPON_FECHA_VENCIMIENTO datetime2(3),
);

CREATE TABLE PEDIDOS_APP.CUPON_RECLAMO(
	CUPON_RECLAMO_NRO decimal(18,0) PRIMARY KEY,
	CUPON_RECLAMO_MONTO decimal(18,2),
	CUPON_RECLAMO_FECHA_ALTA datetime2 (3),
	CUPON_RECLAMO_FECHA_VENCIMIENTO datetime2(3),
	CUPON_RECLAMO_TIPO nvarchar(50),
	RECLAMO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.USUARIO_X_CUPON(
	USUARIO_X_CUPON_NRO INT IDENTITY(1,1) PRIMARY KEY,
	CUPON_NRO decimal(18,0),
	USUARIO_DNI decimal(18,0)
);


CREATE TABLE PEDIDOS_APP.PEDIDO_X_CUPON(
	PEDIDO_X_CUPON_NRO INT IDENTITY(1,1) PRIMARY KEY,
	CUPON_NRO decimal(18,0),
	PEDIDO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.PRODUCTO_X_PEDIDO(
	PRODUCTO_X_PEDIDO INT IDENTITY(1,1) PRIMARY KEY,
	PEDIDO_NRO decimal(18,0),
	PRODUCTO_LOCAL_CODIGO nvarchar(50),
	PRODUCTO_CANTIDAD decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.PRODUCTO_LOCAL(
	PRODUCTO_LOCAL_CODIGO nvarchar(50) PRIMARY KEY,
	PRODUCTO_LOCAL_PRECIO decimal(18,2),
	PRODUCTO_LOCAL_NOMBRE nvarchar(50),
	PRODUCTO_LOCAL_DESCRIPCION nvarchar(255),
	LOCAL_CODIGO nvarchar(50),
);

CREATE TABLE PEDIDOS_APP.PEDIDO(
	PEDIDO_NRO decimal(18,0) PRIMARY KEY,
	PEDIDO_TOTAL_PRODUCTOS decimal(18,2),
	PEDIDO_PRECIO_ENVIO decimal(18,2),
	PEDIDO_TARIFA_SERVICIO decimal(18,2),
	PEDIDO_PROPINA decimal(18,2),
	PEDIDO_OBSERV nvarchar(255),
	PEDIDO_TOTAL_CUPONES decimal(18,2),
	PEDIDO_TOTAL_SERVICIO decimal(18,2),
	PEDIDO_FECHA datetime2(3),
	PEDIDO_FECHA_ENTREGA datetime2(3),
	PEDIDO_TIEMPO_ESTIMADO_ENTREGA decimal(18,2),
	MEDIO_DE_PAGO_NRO_TARJETA nvarchar(50),
	LOCAL_CODIGO nvarchar(50),
	USUARIO_DNI decimal(18,0),
	/*REPARTIDOR_DNI decimal(18,0) No se si ponerlo al dni del repartido aca o en otro envio*/
);

CREATE TABLE PEDIDOS_APP.USUARIO(
	USUARIO_DNI decimal(18,0) PRIMARY KEY,
	USUARIO_NOMBRE nvarchar(255),
	USUARIO_APELLIDO nvarchar(255),
	USUARIO_FECHA_REGISTRO datetime2(3),
	USUARIO_TELEFONO decimal(18,0),
	USUARIO_MAIL nvarchar(255),
	USUARIO_FECHA_NAC date,
	MEDIO_DE_PAGO_NRO_TARJETA nvarchar(50)
);

CREATE TABLE PEDIDOS_APP.USUARIO_DIRECCION (
	USUARIO_DNI decimal(18,0),
	USUARIO_DIRECCION_COD nvarchar(50) PRIMARY KEY,
	USUARIO_DIRECCION nvarchar(255),
	USUARIO_LOCALIDAD nvarchar(255),
	USUARIO_PROVINCIA nvarchar(255)
);

CREATE TABLE PEDIDOS_APP.REPARTIDOR(
	REPARTIDOR_DNI decimal(18,0) PRIMARY KEY,
	REPARTIDOR_NOMBRE nvarchar(255),
	REPARTIDOR_APELLIDO nvarchar(255),
	REPARTIDOR_TELEFONO decimal(18,0),
	REPARTIDOR_MAIL nvarchar(255),
	REPARTIDOR_FECHA_NAC date,
	TIPO_MOVILIDAD_COD DECIMAL(18,0)
);/*Decidir si ponerle la direccion como una fk o como nvchar como en el master
	Ademas de que no existe el tipo envio como si en la tabla, */


CREATE TABLE PEDIDOS_APP.OPERADOR(
	OPERADOR_DNI decimal(18,0) PRIMARY KEY,
	OPERADOR_NOMBRE nvarchar(255),
	OPERADOR_APELLIDO nvarchar(255),
	OPERADOR_TELEFONO decimal(18,0),
	OPERADOR_MAIL nvarchar(255),
	OPERADOR_FECHA_NAC date,
);/*Decidir si ponerle la direccion como una fk o como nvchar como en el master*/


CREATE TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR(
	RECLAMO_X_OPERADOR_NRO INT IDENTITY(1,1) PRIMARY KEY,
	OPERADOR_DNI decimal(18,0),
	RECLAMO_NRO decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.ENVIO_MENSAJERIA(
	ENVIO_MENSAJERIA_NRO decimal(18,2) PRIMARY KEY,
	ENVIO_MENSAJERIA_DIR_ROIG nvarchar(255),
	ENVIO_MENSAJERIA_DIR_DEST nvarchar(255),
	ENVIO_MENSAJERIA_LOCALIDAD nvarchar(255),
	ENVIO_MENSAJERIA_PROVINCIA nvarchar(255),
	ENVIO_MENSAJERIA_KM decimal(18,2),
	ENVIO_MENSAJERIA_VALOR_ASEGURADO decimal(18,2),
	ENVIO_MENSAJERIA_PRECIO_ENVIO decimal(18,2),
	ENVIO_MENSAJERIA_PRECIO_SEGURO decimal(18,2),
	ENVIO_MENSAJERIA_PROPINA decimal (18,2),
	ENVIO_MENSAJERIA_TOTAL decimal(18,2),
	ENVIO_MENSAJERIA_OBSERV nvarchar(255),
	ENVIO_MENSAJERIA_FECHA datetime,
	ENVIO_MENSAJERIA_ENTREGA datetime,
	ENVIO_MENSAJERIA_TIEMPO_ESTIMADO decimal(18,2),
	ENVIO_MENSAJERIA_CALIFICACION decimal(18,0),
	USUARIO_DNI decimal(18,0),
	REPARTIDOR_DNI decimal(18,0),
	MEDIO_PAGO_NRO_TARJETA nvarchar(50),
	PAQUETE_NRO decimal(18,0)
);


CREATE TABLE PEDIDOS_APP.MEDIO_PAGO(
	MEDIO_PAGO_NRO_TARJETA nvarchar(50) PRIMARY KEY,
	MEDIO_PAGO_TIPO nvarchar(50),
	MARCA_TARJETA nvarchar(100),
	USUARIO_DNI decimal(18,0)
);

CREATE TABLE PEDIDOS_APP.PAQUETE(
	PAQUETE_NRO decimal(18,0) PRIMARY KEY,
	PAQUETE_TIPO nvarchar(50),
	PAQUETE_ALTO_MAX decimal(18,2),
	PAQUETE_ANCHO_MAX decimal(18,2),
	PAQUETE_LARGO_MAX decimal(18,2),
	PAQUETE_PESO_MAX decimal(18,2),
	PAQUETE_TIPO_PRECIO decimal(18,2),
	ENVIO_MENSAJERIA_NRO decimal(18,2)
);

CREATE TABLE PEDIDOS_APP.HORARIO_LOCAL(
	HORARIO_LOCAL_NRO decimal(18,0) PRIMARY KEY,
	HORARIO_LOCAL_HORA_APERTURA decimal(18,0),
	HORARIO_LOCAL_HORA_CIERRE decimal(18,0),
	HORARIO_LOCAL_DIA nvarchar(50),
	LOCAL_CODIGO nvarchar(50)
);

CREATE TABLE PEDIDOS_APP.LOCAL(
	LOCAL_CODIGO nvarchar(50) PRIMARY KEY , 
	LOCAL_NOMBRE nvarchar(100) ,
	LOCAL_DESCRIPCION nvarchar(255) ,
	LOCAL_DIRECCION nvarchar(255) ,
	LOCAL_TIPO nvarchar(50) ,
	LOCAL_LOCALIDAD nvarchar(255) ,
	LOCAL_PROVINCIA nvarchar(255) ,
	LOCAL_TELEFONO decimal(18,2) , /*Chequear NULL*/
	LOCAL_CATEGORIA nvarchar(255) , /*Chequear NULL*/
	HORARIO_LOCAL_NRO decimal(18,0),

);

CREATE TABLE PEDIDOS_APP.TIPO_MOVILIDAD(
    TIPO_MOVILIDAD_COD decimal(18,0) PRIMARY KEY,
    TIPO_MOVILIDAD_VEHICULO nvarchar(50),
);

/* CREACION DE FOREIGN KEYS */
ALTER TABLE PEDIDOS_APP.ENVIO ADD CONSTRAINT FK_ENVIO_REPARTIDOR_DNI FOREIGN KEY (REPARTIDOR_DNI) REFERENCES PEDIDOS_APP.REPARTIDOR(REPARTIDOR_DNI)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO ADD CONSTRAINT FK_ENVIO_PEDIDO_NRO FOREIGN KEY (PEDIDO_NRO) REFERENCES PEDIDOS_APP.PEDIDO(PEDIDO_NRO)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO ADD CONSTRAINT FK_RECLAMO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO ADD CONSTRAINT FK_RECLAMO_PEDIDO_NRO FOREIGN KEY (PEDIDO_NRO) REFERENCES PEDIDOS_APP.PEDIDO(PEDIDO_NRO)
GO

ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON ADD CONSTRAINT FK_USUARIO_CUPON_NRO FOREIGN KEY (CUPON_NRO) REFERENCES PEDIDOS_APP.CUPON(CUPON_NRO)
GO

ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON ADD CONSTRAINT FK_U_X_C_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO_X_CUPON ADD CONSTRAINT FK_P_X_C_PEDIDO_NRO FOREIGN KEY (PEDIDO_NRO) REFERENCES PEDIDOS_APP.PEDIDO(PEDIDO_NRO)
GO

ALTER TABLE PEDIDOS_APP.CUPON_RECLAMO ADD CONSTRAINT FK_CUPONR_RECLAMO_NRO FOREIGN KEY (RECLAMO_NRO) REFERENCES PEDIDOS_APP.RECLAMO(RECLAMO_NRO)
GO

ALTER TABLE PEDIDOS_APP.PRODUCTO_X_PEDIDO ADD CONSTRAINT FK_PRODUCTO_X_PEDIDO_NRO FOREIGN KEY (PEDIDO_NRO) REFERENCES PEDIDOS_APP.PEDIDO(PEDIDO_NRO)
GO

ALTER TABLE PEDIDOS_APP.PRODUCTO_LOCAL ADD CONSTRAINT FK_PRODUCTO_LOCAL_LOCAL_CODIGO FOREIGN KEY (LOCAL_CODIGO) REFERENCES PEDIDOS_APP.LOCAL(LOCAL_CODIGO)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_PEDIDO_LOCAL_CODIGO FOREIGN KEY (LOCAL_CODIGO) REFERENCES PEDIDOS_APP.LOCAL(LOCAL_CODIGO)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_PEDIDO_MEDIO_PAGO_NRO_TARJETA FOREIGN KEY (MEDIO_DE_PAGO_NRO_TARJETA) REFERENCES PEDIDOS_APP.MEDIO_PAGO(MEDIO_PAGO_NRO_TARJETA)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_PEDIDO_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

/*
ALTER TABLE PEDIDOS_APP.PEDIDO ADD CONSTRAINT FK_REPARTIDOR_DNI FOREIGN KEY (REPARTIDOR_DNI) REFERENCES PEDIDOS_APP.REPARTIDOR(REPARTIDOR_DNI)
GO
Este es si nos decidimos si el pedido cuenta como envio y ponemos el DNI del repartidor ahi o no
*/

ALTER TABLE PEDIDOS_APP.USUARIO ADD CONSTRAINT FK_USUARIO_MEDIO_PAGO_NRO FOREIGN KEY (MEDIO_DE_PAGO_NRO_TARJETA) REFERENCES PEDIDOS_APP.MEDIO_PAGO(MEDIO_PAGO_NRO_TARJETA)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR ADD CONSTRAINT FK_RECLAMO_X_OPERADOR_RECLAMO_NRO FOREIGN KEY (RECLAMO_NRO) REFERENCES PEDIDOS_APP.RECLAMO(RECLAMO_NRO)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO_X_OPERADOR ADD CONSTRAINT FK_RECLAMO_X_OPERADOR_OPERADOR_DNI FOREIGN KEY (OPERADOR_DNI) REFERENCES PEDIDOS_APP.OPERADOR(OPERADOR_DNI)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_ENVIO_MENSAJERIA_REPARTIDOR_DNI FOREIGN KEY (REPARTIDOR_DNI) REFERENCES PEDIDOS_APP.REPARTIDOR(REPARTIDOR_DNI)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_ENVIO_MENSAJERIA_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_ENVIO_MENSAJERIA_MEDIO_PAGO_NRO_TARJETA FOREIGN KEY (MEDIO_PAGO_NRO_TARJETA) REFERENCES PEDIDOS_APP.MEDIO_PAGO(MEDIO_PAGO_NRO_TARJETA)
GO

ALTER TABLE PEDIDOS_APP.ENVIO_MENSAJERIA ADD CONSTRAINT FK_ENVIO_MENSAJERIA_PAQUETE_NRO FOREIGN KEY (PAQUETE_NRO) REFERENCES PEDIDOS_APP.PAQUETE(PAQUETE_NRO)
GO

ALTER TABLE PEDIDOS_APP.USUARIO_DIRECCION ADD CONSTRAINT FK_USUARIO_DIRECCION_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.MEDIO_PAGO ADD CONSTRAINT FK_MEDIO_PAGO_USUARIO_DNI FOREIGN KEY (USUARIO_DNI) REFERENCES PEDIDOS_APP.USUARIO(USUARIO_DNI)
GO

ALTER TABLE PEDIDOS_APP.PAQUETE ADD CONSTRAINT FK_PAQUETE_ENVIO_MENSAJERIA_NRO FOREIGN KEY (ENVIO_MENSAJERIA_NRO) REFERENCES PEDIDOS_APP.ENVIO_MENSAJERIA(ENVIO_MENSAJERIA_NRO)
GO

ALTER TABLE PEDIDOS_APP.HORARIO_LOCAL ADD CONSTRAINT FK_HORARIO_LOCAL_LOCAL_CODIGO FOREIGN KEY (LOCAL_CODIGO) REFERENCES PEDIDOS_APP.LOCAL(LOCAL_CODIGO)
GO

ALTER TABLE PEDIDOS_APP.LOCAL ADD CONSTRAINT FK_LOCAL_HORARIO_LOCAL_NRO FOREIGN KEY (HORARIO_LOCAL_NRO) REFERENCES PEDIDOS_APP.HORARIO_LOCAL(HORARIO_LOCAL_NRO)
GO

ALTER TABLE PEDIDOS_APP.REPARTIDOR ADD CONSTRAINT FK_REPARTIDOR_TIPO_MOVILIDAD_COD FOREIGN KEY (TIPO_MOVILIDAD_COD) REFERENCES PEDIDOS_APP.TIPO_MOVILIDAD(TIPO_MOVILIDAD_COD)
GO

