/* CREANDO SCHEMA */

CREATE SCHEMA PEDIDOS_APP
GO

/* CREANDO TABLAS */

CREATE TABLE PEDIDOS_APP.RECLAMO(
	id_reclamo CHAR(8) PRIMARY KEY,
	tipo CHAR(20),
	estado CHAR(8),
	descripcion CHAR(500),
	solucion CHAR(500),
	fecha_hora DATE,
	calificacion decimal(1),
	ID_USUARIO CHAR(8),
	ID_PEDIDO CHAR(8)
);

CREATE TABLE PEDIDOS_APP.CÚPON(
	ID_CUPON CHAR(8) PRIMARY KEY,
	detalle char(50),
	tipo char(50)
);

CREATE TABLE PEDIDOS_APP.RECLAMO_X_CUPON(
	ID_RECLAMO_X_CUPON CHAR(8) PRIMARY KEY,
	ID_CUPON CHAR(8),
	ID_RECLAMO CHAR(8)
);

CREATE TABLE PEDIDOS_APP.USUARIO_X_CUPON(
	ID_USUARIO_X_CUPON CHAR(8) PRIMARY KEY,
	ID_CUPON CHAR(8),
	ID_USUARIO CHAR(8)
);

CREATE TABLE PEDIDOS_APP.PEDIDO_X_CUPON(
	ID_PEDIDO_X_CUPON CHAR(8) PRIMARY KEY,
	ID_CUPON CHAR(8),
	ID_PEDIDO CHAR(8)
);


/* CREACION DE FOREIGN KEYS */

ALTER TABLE PEDIDOS_APP.RECLAMO ADD CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES M_AL_CUBO.USUARIO(ID_USUARIO)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO ADD CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES M_AL_CUBO.PEDIDO(ID_PEDIDO)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO_X_CUPON ADD CONSTRAINT FK_ID_CUPON FOREIGN KEY (ID_CUPON) REFERENCES M_AL_CUBO.CUPON(ID_CUPON)
GO

ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON ADD CONSTRAINT FK_ID_CUPON FOREIGN KEY (ID_CUPON) REFERENCES M_AL_CUBO.CUPON(ID_CUPON)
GO

ALTER TABLE PEDIDOS_APP.USUARIO_X_CUPON ADD CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES M_AL_CUBO.USUARIO(ID_USUARIO)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO_X_CUPON ADD CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES M_AL_CUBO.PEDIDO(ID_PEDIDO)
GO

ALTER TABLE PEDIDOS_APP.PEDIDO_X_CUPON ADD CONSTRAINT FK_ID_CUPON FOREIGN KEY (ID_CUPON) REFERENCES M_AL_CUBO.CUPON(ID_CUPON)
GO

ALTER TABLE PEDIDOS_APP.RECLAMO_X_CUPON ADD CONSTRAINT FK_ID_RECLAMO FOREIGN KEY (ID_RECLAMO) REFERENCES M_AL_CUBO.RECLAMO(ID_RECLAMO)
GO

